### ISSUE TITLE
TypeError with sinon stubs.

### ISSUE THREAD

**Issue by viudu** [sinet/lapin-mock#2]
@gideonairex @yamii

In using lapin-mock today following your Readme - was getting errors when trying to run the tests 

```
TypeError: Attempted to wrap request which is already wrapped
      at Context.<anonymous> (test/services/content/v1.legacy-content.get-by-ids-test.js:29:22)
```

I was able to get around this by restoring the sinon stubs with the after function, placed in each describe section: 

``` js
after( function () {
    rabbitAPI.request.restore();
    rabbitAPI.respond.restore();
} );
```

If this is correct, please update the readme.

**Comment by gideonairex** [comment]
@viudu yes forgot to add that in the README Thanks for that!

**Comment by gideonairex** [comment]
@viudu can we close this issue now?

**Comment by viudu** [comment]
Yep - thanks for the reminder
